apiVersion: v1
kind: ConfigMap
metadata:
  name: ama-metrics-settings-configmap
  namespace: kube-system
data:
  schema-version:
    "v1"
  config-version:
    "v1"
  # 🚀 THIS IS THE SWITCH THAT TELLS AZURE TO SCRAPE YOUR HELM POD ANNOTATIONS
  pod-annotation-metric-scraping-enabled:
    "true"