apiVersion: v1
kind: Secret
metadata:
  name: gradestar-secrets
  namespace: default
type: Opaque
data:
  # Values must be Base64 encoded strings
  database-password: KVFMRWMkaVo4WHNqX2o3OHp7Wyp2R01l
  app-key: YmFzZTY0OnJocEFicDRmRDZBSHNYWEdOZjBLdHFVM1JjTTFVemNKM0cxR21hK3lBbUU9