apiVersion: v1
kind: Secret
metadata:
  name: gradestar-secrets
  namespace: default
type: Opaque
data:
  # Values must be Base64 encoded strings
  database-password: ZipwaDM9RSRzal9QUUh2WU03eTo+VFhO
  app-key: YmFzZTY0OnJocEFicDRmRDZBSHNYWEdOZjBLdHFVM1JjTTFVemNKM0cxR21hK3lBbUU9