apiVersion: v1
kind: Secret
metadata:
  name: gradestar-secrets
  namespace: default
type: Opaque
data:
  # Values must be Base64 encoded strings
  database-password: cGFzc3dvcmQ=
  app-key: rhpAbp4fD6AHsYXGNf0KtqU3RcM1UzcJ3G1Gma+yAmE=